language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio update
script:
- mkdir build
- platformio ci --keep-build-dir --build-dir ./build --project-conf=platformio.ini
  src/main.cpp
before_deploy:
- platformio ci -h
- ls -a
- find . -name "*.bin"
deploy:
  provider: releases
  api_key:
    secure: nBYCWD2QpaR9LQQ1nqkKXezij46nn2AJvcQnpwbYpXGD08Ik5enUucq4h2WNz6moVjWSRyA8Trb5DdLTtYSnCJCxBYueA9G2FP6Z38bUsezgcsrns8qVQT1tzX1Dh4vOOP8TM/2/DAGkW149QmVhD8vU6XD9X9qkzfjbWXShP//VExNpr3nLyp0KvB+L4rh1EtumSMUzwPIMcplFH/9/z4PQnwwJiYLhvOwa0EWMgn7W/LVjHfKYZvYD7UQr5HCJgzWVhQrGEVzCys5Ywhgy40Q/lmeeTwoNlFQqSuswUO1ZzT1TA+fpliE3p9van62kYJ4O4/IRgswk6JREcOv8ekWwngksUlvuW1QAImHjYhX/GsRz++GulRyi5+31gyZbtcJhAQCLeTtof+VqpEF/MA+o47tc3NAxv5ssr4Jbeq8IOTwOv/e9FvLYmvkiTqkzoeiWcmgOE9aSv+mhuSFEvqDKmb+9mTBKNBf1PqrM5BVk1w/qsjuCkCjVzV50zx/LqN4+YkMkRWcL/Xvafnp8Lv2WjgNiXlVF+lU4/J9nnSvK8LSVjThmI/SdwQmjimurP/GwYemEW6BJwJvwO6814C2mUZEFOkqZhn2KOlCqIiXQKgw1VOwcfIyfNr6C4a6xWYw0gSYMsSnDKz/GmGnKWHE7e8B8u+LnsB8hYPlg4LI=
  file: "build/.pio/build/d1/firmware.bin"
  skip_cleanup: true
  on:
    repo: IoTDevice/esp8266-switch
    tags: true
